# 是否在上传时显示调试数据
debug: false

# 是否跳过生成校验文件阶段
upload_only: false

# 上传完成后，是否不自动退出
show_any_key_to_exit: false

# 上传到哪里？
service_provider: tencent

# 腾讯云对象存储
tencent:
  bucket: 
  secret_id: 
  secret_key: 
  region: ap-nanjing

  # 缓存文件的文件名。用来实现增量上传
  # 此文件会存储到桶里（而不是本地），删除此文件可以进行一次全量上传
  # 只支持放置在桶的根目录（也就是说这里只能填写文件名不能填写一个路径）
  cache_file: .cache.yml

  # 自动设置http headers
  header_rules:
    # 正则表达式(按相对路径匹配，此路径不包含要上传的文件夹本身)
    - pattern: '.gz$'
    # 添加的http headers
      headers:
        Content-Encoding: gzip

# 阿里云对象存储
aliyun:
  bucket: 
  access_id: 
  access_key: 
  region: oss-cn-chengdu.aliyuncs.com

  # 缓存文件的文件名。用来实现增量上传
  # 此文件会存储到桶里（而不是本地），删除此文件可以进行一次全量上传
  # 只支持放置在桶的根目录（也就是说这里只能填写文件名不能填写一个路径）
  cache_file: .cache.yml

  # 自动设置http headers
  header_rules:
    # 正则表达式(按相对路径匹配，此路径不包含要上传的文件夹本身)
    - pattern: '.gz$'
    # 添加的http headers
      headers:
        Content-Encoding: gzip

# FTP/FTPS
ftp:
  host: 127.0.0.1
  port: 21
  user: ab
  password: ab

  # 上传到哪个路径，支持子目录，默认是根目录，这里必须以/开头，结尾不做要求
  base_path: /

  # 缓存文件的文件名。用来实现增量上传
  # 此文件会存储到FTP服务器上（而不是本地），删除此文件可以进行一次全量上传
  # 只支持放置在basePath下（也就是说这里只能填写文件名不能填写一个路径）
  cache_file: .cache.yml

  # 启用TLS加密（FTPS）
  secure: false

  # 高级参数，登录后是否立即发送prot_p命令
  prot_p: false

# SFTP
sftp:
  host: 127.0.0.1
  port: 22
  user: username
  
  # 如果使用 密码认证（usePkey 为 false），请填入密码
  # 如果使用 密钥对认证（usePkey 为true） 且 私钥被加密，请填入私钥密码，否则请留空
  password: password

  # 是否使用密钥对认证
  usePkey: false

  # 私钥文件名，可使用相对路径，目前仅支持 OpenSSH RSA 私钥（格式如下）
  # -----BEGIN RSA PRIVATE KEY-----
  # I9no9NE9sjKCAQEAt0JNJh+DzjjedIIE68sAA2qNi2+AMZy0cMciqLogIBABsBub
  # ...省略多行...
  # TLudhHIwG/0yKSmCtEo5KWl6sqjawFEE0qrWZL3QTP8ofHcEe8c=
  # -----END RSA PRIVATE KEY-----
  pkeyFile: id_rsa

  # 上传到哪个路径，支持子目录，默认是 /tmp 目录防止意外，这里必须以 / 开头（绝对路径），结尾不做要求
  # 警告：此选项必须谨慎填写，如果填写错误可能导致数据丢失或者系统严重损坏！
  # 极其不建议使用 root 用户进行上传，建议新建一个用户专门用于上传，并严格限制其读写权限
  # 建议使用 /home/<user>/updater 这类路径，并只保留上传 user 对自己 home 目录的读写权限
  basePath: /tmp

  # 缓存文件的文件名。用来实现增量上传
  # 此文件会存储到 SFTP 服务器上（而不是本地），删除此文件可以进行一次全量上传
  # 只支持放置在 basePath 下（也就是说这里只能填写文件名不能填写一个路径）
  cache_file: .cache.yml
