on:
  push:
    tags: 
      - "v*"

jobs:
  build:
    runs-on: windows-2019
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Load Cache
        uses: actions/cache@v2
        with: 
          path: .\venv
          key: ${{ hashFiles('**/requirements.txt') }}
      
      - name: Check Out Tag-Name
        id: checkout-tagname
        shell: "python3 {0}"
        run: |
          import os
          import re
          ref = os.getenv('GITHUB_REF', '')
          match = re.search(r'refs\/tags\/(.*)', ref)
          tag_name = match[1] if match is not None else ''
          print('::set-output name=tag_name::'+tag_name)

      - name: Build
        env: 
          tag_name: ${{ steps.checkout-tagname.outputs.tag_name }}
        run: |
          tzutil /s "China Standard Time"
          python -m pip install wheel setuptools virtualenv
          python -m virtualenv venv
          venv\Scripts\activate
          pip install -r requirements.txt

          pyinstaller --noconfirm -i icon.ico -c -F -n Tool src/Tool-${{ env.tag_name }}.py
          copy config.exam.yml dist\config.yml

      - name: Print Hashes
        env: 
          tag_name: ${{ steps.checkout-tagname.outputs.tag_name }}
        run: |
          python ci\hash_tool.py dist\Tool-${{ env.tag_name }}.exe
      
      - name: Upload To Github Release
        uses: xresloader/upload-to-github-release@98857380fc282f8075a62c6af230fe92bd93aff8
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          file: dist/*
          draft: false
          tags: true        
