on:
  push:
    tags: 
      - "v*"

jobs:
  build:
    runs-on: windows-2019
    steps:
      - name: Prepare
        run: tzutil /s "China Standard Time"
        
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Load Cache
        uses: actions/cache@v2
        with: 
          path: ~\AppData\Local\pip\Cache
          key: ${{ runner.os }}-${{ hashFiles('**/requirements.txt') }}
        
      - name: Build
        run: |
          python -m pip install wheel setuptools
          python -m pip install -r requirements.txt
          python ci\generate_version_file.py
          C:\hostedtoolcache\windows\Python\3.7.9\x64\Scripts\pyinstaller --noconfirm --version-file version-file.txt -i icon.ico -F -c -n UtilityTool main.py
          Copy-Item config.exam.yml dist\
          dir

      - name: Print Hashes
        run: |
          python ci\version.py both
          echo "---------------------------"
          echo "MD5 for dist\UtilityTool.exe:"
          python ci\sha1.py dist\UtilityTool.exe
          echo "SHA1 for dist\UtilityTool.exe:"
          python ci\md5.py dist\UtilityTool.exe
      
      - name: Upload To Github Release
        uses: xresloader/upload-to-github-release@v1.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          file: dist/*
          draft: false
          tags: true        
