on:
  push:
    tags: 
      - "v*"

jobs:
  build:
    runs-on: windows-2019
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Load Cache
        uses: actions/cache@v2
        with: 
          path: .\venv
          key: ${{ hashFiles('**/requirements.txt') }}
        
      - name: Build
        run: |
          tzutil /s "China Standard Time"
          python -m pip install wheel setuptools virtualenv
          python -m virtualenv venv
          venv\Scripts\activate
          pip install -r requirements.txt
          
          python ci\generate_version_file.py
          pyinstaller --noconfirm --version-file version-file.txt -i icon.ico -F -c -n Tool main.py
          copy config.exam.yml dist\config.yml
          
          dir
          dir dist

      - name: Print Hashes
        run: |
          python ci\version.py both
          echo "---------------------------"
          echo "MD5 for dist\Tool.exe:"
          python ci\sha1.py dist\Tool.exe
          echo "SHA1 for dist\Tool.exe:"
          python ci\md5.py dist\Tool.exe
      
      - name: Upload To Github Release
        uses: xresloader/upload-to-github-release@98857380fc282f8075a62c6af230fe92bd93aff8
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          file: dist/*
          draft: false
          tags: true        
